# Generated by Django 5.1.12 on 2025-10-15 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_course_summary_es_course_summary_fr_course_title_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadvideo",
            name="is_youtube_video",
            field=models.BooleanField(
                default=False, help_text="Automatically set if YouTube URL is provided"
            ),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="video_duration",
            field=models.CharField(
                blank=True, help_text="Video duration (auto-populated)", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="youtube_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube video URL (e.g., https://www.youtube.com/watch?v=VIDEO_ID)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="uploadvideo",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Valid video formats: mp4, mkv, wmv, 3gp, f4v, avi, mp3 (Optional if YouTube URL is provided)",
                null=True,
                upload_to="course_videos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["mp4", "mkv", "wmv", "3gp", "f4v", "avi", "mp3"]
                    )
                ],
            ),
        ),
    ]
