# Generated by Django 5.1.12 on 2025-10-15 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0004_uploadvideo_is_youtube_video_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watch_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Watch time in seconds"
                    ),
                ),
                (
                    "total_duration",
                    models.PositiveIntegerField(
                        default=0, help_text="Total video duration in seconds"
                    ),
                ),
                (
                    "last_position",
                    models.PositiveIntegerField(
                        default=0, help_text="Last watched position in seconds"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "completion_percentage",
                    models.FloatField(
                        default=0.0, help_text="Completion percentage (0-100)"
                    ),
                ),
                ("first_watched", models.DateTimeField(auto_now_add=True)),
                ("last_watched", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"is_student": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="course.uploadvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_watched"],
                "unique_together": {("student", "video")},
            },
        ),
    ]
