# Generated by Django 5.2.7 on 2025-10-15 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0003_choice_choice_es_choice_choice_fr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="content_en",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_es",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_fr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_ru",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_en",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_es",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_fr",
        ),
        migrations.RemoveField(
            model_name="question",
            name="explanation_ru",
        ),
    ]
